# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kuavo_person_follow/PersonState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PersonState(genpy.Message):
  _md5sum = "ff2a122bd34c3d20e5271bb623e20485"
  _type = "kuavo_person_follow/PersonState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x        # 左右偏移 (m)，左为正（base_link 坐标系）
float32 z        # 前后距离 (m)，前方为正
float32 vx       # x 方向速度 (m/s)
float32 vz       # z 方向速度 (m/s)
float32 yaw_err  # 朝向误差 (rad)，>0 目标在左侧
bool   valid     # 当前是否有可靠目标
float32 confidence  # 0~1, 置信度
"""
  __slots__ = ['x','z','vx','vz','yaw_err','valid','confidence']
  _slot_types = ['float32','float32','float32','float32','float32','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,z,vx,vz,yaw_err,valid,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PersonState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.z is None:
        self.z = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vz is None:
        self.vz = 0.
      if self.yaw_err is None:
        self.yaw_err = 0.
      if self.valid is None:
        self.valid = False
      if self.confidence is None:
        self.confidence = 0.
    else:
      self.x = 0.
      self.z = 0.
      self.vx = 0.
      self.vz = 0.
      self.yaw_err = 0.
      self.valid = False
      self.confidence = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5fBf().pack(_x.x, _x.z, _x.vx, _x.vz, _x.yaw_err, _x.valid, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.x, _x.z, _x.vx, _x.vz, _x.yaw_err, _x.valid, _x.confidence,) = _get_struct_5fBf().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5fBf().pack(_x.x, _x.z, _x.vx, _x.vz, _x.yaw_err, _x.valid, _x.confidence))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.x, _x.z, _x.vx, _x.vz, _x.yaw_err, _x.valid, _x.confidence,) = _get_struct_5fBf().unpack(str[start:end])
      self.valid = bool(self.valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5fBf = None
def _get_struct_5fBf():
    global _struct_5fBf
    if _struct_5fBf is None:
        _struct_5fBf = struct.Struct("<5fBf")
    return _struct_5fBf
