// Generated by gencpp from file kuavo_person_follow/PersonState.msg
// DO NOT EDIT!


#ifndef KUAVO_PERSON_FOLLOW_MESSAGE_PERSONSTATE_H
#define KUAVO_PERSON_FOLLOW_MESSAGE_PERSONSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_person_follow
{
template <class ContainerAllocator>
struct PersonState_
{
  typedef PersonState_<ContainerAllocator> Type;

  PersonState_()
    : x(0.0)
    , z(0.0)
    , vx(0.0)
    , vz(0.0)
    , yaw_err(0.0)
    , valid(false)
    , confidence(0.0)  {
    }
  PersonState_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)
    , vx(0.0)
    , vz(0.0)
    , yaw_err(0.0)
    , valid(false)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _z_type;
  _z_type z;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _yaw_err_type;
  _yaw_err_type yaw_err;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::kuavo_person_follow::PersonState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_person_follow::PersonState_<ContainerAllocator> const> ConstPtr;

}; // struct PersonState_

typedef ::kuavo_person_follow::PersonState_<std::allocator<void> > PersonState;

typedef boost::shared_ptr< ::kuavo_person_follow::PersonState > PersonStatePtr;
typedef boost::shared_ptr< ::kuavo_person_follow::PersonState const> PersonStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_person_follow::PersonState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_person_follow::PersonState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_person_follow::PersonState_<ContainerAllocator1> & lhs, const ::kuavo_person_follow::PersonState_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.z == rhs.z &&
    lhs.vx == rhs.vx &&
    lhs.vz == rhs.vz &&
    lhs.yaw_err == rhs.yaw_err &&
    lhs.valid == rhs.valid &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_person_follow::PersonState_<ContainerAllocator1> & lhs, const ::kuavo_person_follow::PersonState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_person_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_person_follow::PersonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_person_follow::PersonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_person_follow::PersonState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff2a122bd34c3d20e5271bb623e20485";
  }

  static const char* value(const ::kuavo_person_follow::PersonState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff2a122bd34c3d20ULL;
  static const uint64_t static_value2 = 0xe5271bb623e20485ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_person_follow/PersonState";
  }

  static const char* value(const ::kuavo_person_follow::PersonState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x        # 左右偏移 (m)，左为正（base_link 坐标系）\n"
"float32 z        # 前后距离 (m)，前方为正\n"
"float32 vx       # x 方向速度 (m/s)\n"
"float32 vz       # z 方向速度 (m/s)\n"
"float32 yaw_err  # 朝向误差 (rad)，>0 目标在左侧\n"
"bool   valid     # 当前是否有可靠目标\n"
"float32 confidence  # 0~1, 置信度\n"
;
  }

  static const char* value(const ::kuavo_person_follow::PersonState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
      stream.next(m.vx);
      stream.next(m.vz);
      stream.next(m.yaw_err);
      stream.next(m.valid);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_person_follow::PersonState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_person_follow::PersonState_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "yaw_err: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_err);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_PERSON_FOLLOW_MESSAGE_PERSONSTATE_H
